CI: run internal unit tests only once
Internal tests take a non-negligible duration: run them only once in CI.
This way, CI is faster.

To manually run them, use `ndpiReader --run-tests`; note that this way
the application runs ONLY these tests.

diff --git a/tests/do.sh.in b/tests/do.sh.in
--- a/tests/do.sh.in
+++ b/tests/do.sh.in
@@ -79,6 +79,7 @@ PLUGINS_CFGS="plugins"
 ABS_SRCDIR="@abs_top_srcdir@"
 ABS_BUILDDIR="@abs_top_builddir@"
 READER="${CMD_PREFIX} ../../../example/ndpiReader${EXE_SUFFIX} --cfg=filename.config,../../../example/config.txt -A -p ../../..//example/protos.txt -c ../../..//example/categories.txt -r ../../../example/risky_domains.txt -j ../../../example/ja4_fingerprints.csv -S ../../..//example/sha1_fingerprints.csv -G ../../../lists -L ../../../lists/public_suffix_list.dat -q -K JSON -k /dev/null -t -v 2"
+READER_UTESTS="${CMD_PREFIX} ./example/ndpiReader${EXE_SUFFIX} --run-tests"
 #Used by plugins; different variables for Linux and macOS: no harm in setting always both of them
 LD_LIBRARY_PATH=${ABS_BUILDDIR}/src/lib/
 DYLD_LIBRARY_PATH=${ABS_BUILDDIR}/src/lib/
@@ -320,6 +321,16 @@ process_single_config() {
     return $RET
 }
 export -f process_single_config
+
+# Run (once) internal unit tests
+cd ${ABS_BUILDDIR}
+$READER_UTESTS
+RC=$?
+if [ $RC -ne 0 ]; then
+    echo "Error internl unit tests"
+    exit $RC
+fi
+cd -
 
 if [ $FUZZY_TESTING_ENABLED -eq 1 ]; then
     fuzzy_testing
